#  yaml-language-server: $schema=https://taskfile.dev/schema.json
# docs: https://taskfile.dev
---
version: "3"

includes:
  internal: internal.yml

tasks:
  # * Install Gitleaks
  install:gitleaks:
    desc: Install Gitleaks
    cmds:
      - task: internal:install:winget
        vars:
          APP: "Gitleaks.Gitleaks"
      - task: internal:install:brew
        vars:
          APP: gitleaks
      - cmd: |
          arch=$(uname -m)
          if [[ "${arch}" == "x86_64" ]]; then
            arch="x64"
          elif [[ "${arch}" == "aarch64" ]]; then
            arch="arm64"
          else
            echo "Unsupported architecture: ${arch}"
            exit 1
          fi
          download_url=$(curl --location --silent "https://api.github.com/repos/gitleaks/gitleaks/releases/latest" | grep 'browser_download_url.*gitleaks.*linux_'"${arch}"'.*tar.gz"' | grep -o 'https://[^"]*')
          curl --location -o /tmp/gitleaks.tar.gz "${download_url}"
          tar -xf /tmp/gitleaks.tar.gz --directory /tmp
          rm /tmp/gitleaks.tar.gz
          sudo mv /tmp/gitleaks /usr/local/bin/gitleaks
        platforms: [linux]

  # * Install Trivy
  install:trivy:
    desc: Install Trivy
    cmds:
      - task: internal:install:winget
        vars:
          APP: "AquaSecurity.Trivy"
      - task: internal:install:brew
        vars:
          APP: trivy
      - cmd: |
          sudo apt-get install wget gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
        platforms: [linux]

  # * Install Checkov
  install:checkov:
    desc: Install Checkov
    cmds:
      - task: internal:install:pipx
        vars:
          APP: checkov

  # * Tools
  tools:
    desc: Install Security tools
    cmds:
      - task: install:gitleaks
      # - task: install:trivy
      # - task: install:checkov

  # * Lint
  lint:
    desc: Run Security linters
    cmds:
      - gitleaks detect --config "./.github/linters/.gitleaks.toml" --source . --redact=90 --verbose
      # - trivy --config ./.trivy.yml fs .
      # - checkov --config-file ./.checkov.yml --directory .
    dir: "{{.ROOT_DIR}}"
