#  yaml-language-server: $schema=https://taskfile.dev/schema.json
# docs: https://taskfile.dev
#
# --- Windows ---
# winget install Task.Task
#
# --- Linux ---
# sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
# echo 'command -v task >/dev/null || export PATH="$PATH:$HOME/.local/bin"' >> ~/.profile
# source ~/.profile
#
# ---  macOS ---
# brew install go-task/tap/go-task
---
version: "3"

includes:
  internal:
    taskfile: .taskfiles/internal.yml
  sh:
    taskfile: .taskfiles/bash.yml
  gh:
    taskfile: .taskfiles/github.yml
  md:
    taskfile: .taskfiles/markdown.yml
  sec:
    taskfile: .taskfiles/security.yml
  spell:
    taskfile: .taskfiles/spell.yml
  yml:
    taskfile: .taskfiles/yaml.yml

vars:
  REPO_ABS_ROOT_PATH:
    sh: git rev-parse --show-toplevel

tasks:
  default:
    desc: Default task
    silent: true
    cmds:
      - cmd: task --list
        ignore_error: true

  tools:
    desc: Install tools
    cmds:
      - task: sh:tools
      - task: gh:tools
      - task: md:tools
      - task: sec:tools
      - task: spell:tools
      - task: yml:tools

  lint:
    desc: Lint files
    cmds:
      - task: sh:lint
      - task: gh:lint
      - task: sec:lint
      - task: spell:lint
      - task: yml:lint
      - task: md:lint

  lint:ml:
    desc: Lint using MegaLinter
    vars:
      LATEST:
        sh: gh release list --repo oxsecurity/megalinter --exclude-drafts --exclude-pre-releases --json "isLatest,tagName" --jq '.[] | select(.isLatest) | .tagName'
    cmds:
      - docker run -v "{{.REPO_ABS_ROOT_PATH}}":/tmp/lint ghcr.io/oxsecurity/megalinter-cupcake:{{.LATEST}} -e 'SHOW_ELAPSED_TIME=true' --fix
