# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
dictionaries:
  - softwareTerms
  - companies
  - python
  - bash
  - filetypes
  - en_US
allowCompoundWords: true
words:
  - codespell
  - MYENVPREFIX
  - stefanzweifel
