# yaml-language-server: $schema=https://www.schemastore.org/prettierrc.json
# docs: https://prettier.io/docs/configuration
---
printWidth: 160
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: none
bracketSpacing: true
bracketSameLine: false
arrowParens: always
proseWrap: always
endOfLine: lf
embeddedLanguageFormatting: auto
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: true
