# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
# https://yamllint.readthedocs.io/en/stable/configuration.html#extending-the-default-configuration
---
extends: default

locale: en_US.UTF-8

rules:
  line-length: disable
  comments: disable
